### ISSUE TITLE
is it possible to use text paragram to correct generated subtitles?

### ISSUE THREAD

**Issue by xiaohong23** [StevenBaby/davinci_resolve_matching_subtitles#1]
I tried to use text block without timestamps to match the generated subtitle, it didn't work.  I was wondering if this is possible.  Thank you.

**Comment by StevenBaby** [comment]
I guess you want to create text block with generated srt file automatically?

**Comment by xiaohong23** [comment]
No.  I already have text file with correct content of the audio or video file but without timestamps.  What I am looking for is to use the correct text file to replace the not so accurate words in the srt file generated by davinci resolve automatically.

**Comment by StevenBaby** [comment]
The script can create a subtitle file to mediapool by text file of audio or video, you just drag in to subtitle track manually!

I didn't find a way to create a subtitle track automatically.

**Comment by xiaohong23** [comment]
Thank you.  I found a project (Aeneas) more suits my situation.

**Comment by StevenBaby** [comment]
If you want to use this feature independently, I think the project (stable-ts) is easier to use, and (Aeneas)  is harder to configure.
