### ISSUE TITLE
mac下环境配置代码怎么写呀?

### ISSUE THREAD

**Issue by Edwardvi** [StevenBaby/davinci_resolve_matching_subtitles#2]
我用conda建了个环境,然后修改代码,大概是这样

def activate_virtual_env():
    virtual_env_path = '/opt/miniconda3/envs/dafenqi/bin/python3.12'
    try:
        os.system(f'source {virtual_env_path}')
    except Exception as e:
        print(f"Error activating virtual environment: {e}")

def main():
    activate_virtual_env()

一直提示我这个错误

Last login: Tue Sep  3 00:27:38 on ttys011
cd '/Users/m/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility/' && '/usr/local/bin/python3'  '/Users/m/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility/Matching Subtitles.py'  && echo Exit status: $? && exit 1
(base) m@192 ~ % cd '/Users/m/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility/' && '/usr/local/bin/python3'  '/Users/m/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility/Matching Subtitles.py'  && echo Exit status: $? && exit 1
/opt/miniconda3/envs/dafenqi/bin/python: line 1: ????: command not found
Traceback (most recent call last):

**Comment by StevenBaby** [comment]
## 遇到的限制
1. 这个工具应该没法直接执行，是由 davinci 执行的（我没有找到其他调试方法）。
2. davinci 会调用系统默认的 python 来执行，（我没有找到 davinci 修改 python 的选项）
## 解决的方法
在上面两条限制下：
1. 必须使用系统默认的 python，可以简单的直接安装依赖；或者也可以系统默认的 virtualenv，然后在开始调用 virtualenv 的脚本 activate_this.py，这个源码里有写。由于 python 环境不是 shell，所以 `os.system()` 的执行结果是无效的，不能使用 source 来激活 virtualenv。**重点是这里 davinci 只用到了系统默认的 python**。
2. 我猜你只需要把 WORKON_HOME 那里改成:
  ```python
  activate_this = '$WORKON_HOME/davinci/Scripts/activate_this.py'
  ``` 
  然后用系统默认的 python 创建一个名为 davinci 的 virtualenv，然后装完依赖就可以了
  当然还需要 export WORKON_HOME=<davinci 的父目录>，不然也可以改成绝对路径，用于调试。
3. 我没有 mac，希望你解决问题之后反馈一下，让这个工具变得更好。
4. 祝你好运！

**Comment by Edwardvi** [comment]
我使用virtualenv建立虚拟环境,
虚拟环境名称为davinic.

然后修改环境代码为:
```
def main():
    workon = "/Users/m/Documents/Blackmagic Design/davinic"
    if os.path.exists(workon):
        active_this = os.path.join(workon, "bin", "activate_this.py")
        if os.path.exists(active_this):
            exec(compile(open(active_this, "rb").read(), active_this, 'exec'), dict(__file__=active_this))
        # print(active_this)
```
其中 /Users/m/Documents/Blackmagic Design/davinic 为虚拟环境所在的位置,
目前在达芬奇没有报错.
可以匹配文案生成的字幕好像时间轴不太对.
我再试试吧

**Comment by Edwardvi** [comment]
匹配文案需要用另起一行来告诉脚本
脚本是按照每一行为一个字幕 
来分割整个文案的

我目前的测试结果是这样.

**Comment by Edwardvi** [comment]
随便找个AI,把文案去标点符号然后调整为一行一行的格式,丢到文本框里,就可以正确匹配使用了.很棒!
